### ISSUE TITLE
Add Integration Test Suite for Vault and Strategy interactions

### ISSUE THREAD

**Issue by dougstorm** [iearn-finance/brownie-strategy-mix#14]
Add an integration test suite that strategist can use to test their code that works as a smoke test for the minimum features they need to implement and ensures the strategy is working correctly for normal conditions and emergency mode.

This test suite should help ensure the vault and strategy interactions work correctly.

Covers at least the following scenarios:

* Test normal operations of vault + strategy interactions like: 
   * deposit
   * withdrawal
   * harvest
   * tend
* Test extraordinary scenarios like Emergency Exit state and ensure liquidate position can properly exit position

**Comment by steffenix** [comment]
Would like to help.

**Comment by fubuloubu** [comment]
@steffenix greatly appreciated!

**Comment by steffenix** [comment]
The current code forks mainnet, what I had in mind was using existing vaults to build some tests

**Comment by fubuloubu** [comment]
> How do you run tests from an imported module?

This is not a feature Brownie officially supports yet, but if you look at `~/.brownie/packages/...` you'll see that the entire github repository is downloaded at that location. You could dynamically load the test module at that location and import the names into the namespace of an integration test module, and pytest will register and run them.

Very advanced topic, not something you have to accomplish on this first pass of adding an integration suite which tests common actions.

**Comment by fameal** [comment]
#17  was complimentary to this one to add more tests. 

It's desirable to be able to test this additional stuff:
- Profitable harvest
- Revoke strategy and check that funds return to the vault
- Increase/decrease debt + harvest, and check that the strategy is working well
- Migration
- Check that tokens in the strategy cannot be swept by dust collection

**Comment by steffenix** [comment]
> #17 was complimentary to this one to add more tests.
> 
> It's desirable to be able to test this additional stuff...

Ok I will look at this additional tests and take care of it.

Could you explain a bit what the last one means?

```
Check that tokens in the strategy cannot be swept by dust collection
```

**Comment by fameal** [comment]
> Check that tokens in the strategy cannot be swept by dust collection
Dust collection is a function that allows getting tokens sent to the contract. But, some tokens are protected. For example, if you have a strategy that farms COMP to dump and accrue yield. COMP tokens are protected. In that case, the test should assure the COMP is not collected using the dust collection function.

> Profitable harvest
I agree with leaving Strategy.sol as close as possible to a boilerplate. I've talked about this with @Macarse. Any ideas?

**Comment by steffenix** [comment]
I think we could add instructions on how to create a test, with the fixture it's not going to be a lot of code.

- create a new tests.
- Deposit to the vault
- Call harvest
- Advance in time
- Call harvest again
- assert balance increased

**Comment by fubuloubu** [comment]
I was thinking this could be a test file with a bunch of `TODO` comments

**Comment by steffenix** [comment]
> I was thinking this could be a test file with a bunch of `TODO` comments

ok

**Comment by steffenix** [comment]
@fameal could you point me to some code to help me understand the `dust collection function` I am still having a hard time understanding.

**Comment by fameal** [comment]
Check this test out:
https://github.com/iearn-finance/yearn-vaults/blob/6ba0909826f7eb5a9671b9c047687c8b519f0e77/tests/functional/strategy/test_misc.py#L77

It'd be good to have something similar here in the strategy mix

**Comment by fubuloubu** [comment]
This is why I want to make the Vault's test suite importable lol

**Comment by dougstorm** [comment]
I know carlos and Sam and Emiliano and also the Vaults repo have some very good tests that we can port into this repo for this task, other good smoke tests.

- Test normal deposit/withdraws
- Test emergency conditions, deposit/withdraw still work under emergency state for vault
- Test migrations of strategy (can be a template test strategy just assert balance was correctly migrated and not stuck)
- Test Revoke Strategy works
- Test Harvest and Tend don`t revert
- Test HarvestTrigger and TendTrigger don't Revert

These are like basic smoke tests, strategist will of course add more meat around their specific logic, but this gives them a good footing to start on and check logic passes minimum requirements

**Comment by steffenix** [comment]
Most of the tests you suggest has been added already.

- Test normal deposit/withdraws: https://github.com/iearn-finance/brownie-strategy-mix/blob/master/tests/test_operation.py#L4
- Test emergency conditions -> can be added
- Test migrations of strategy: https://github.com/iearn-finance/brownie-strategy-mix/pull/22
- Test Revoke Strategy works: https://github.com/iearn-finance/brownie-strategy-mix/pull/22/files
- Test Harvest and Tend don`t revert: https://github.com/iearn-finance/brownie-strategy-mix/blob/master/tests/test_operation.py#L11
- Test HarvestTrigger and TendTrigger don't Revert -> Can be added.

**Comment by fameal** [comment]
@dougstorm do you think we can close this? Is there anything missing?

**Comment by fubuloubu** [comment]
Closing remainder of work in favor of https://github.com/iearn-finance/brownie-strategy-mix/issues/14
