### ISSUE TITLE
Create generic test scripts to check the strategy is working fine

### ISSUE THREAD

**Issue by fameal** [iearn-finance/brownie-strategy-mix#17]
Add generic test to be able to tell if basic functionality is working fine.

This can be used as the base scripts needed: https://github.com/Macarse/yhegic/tree/master/tests/development

**Comment by steffenix** [comment]
Will help

**Comment by steffenix** [comment]
How is that task different from https://github.com/iearn-finance/brownie-strategy-mix/issues/14 ?

**Comment by fubuloubu** [comment]
> How is that task different from #14 ?

It's not lol
